### PR TITLE
build: bump pylint version 1.7.5 > 1.8.2

### PR DESCRIPTION
**Pull request by simobasso**
in order to fix `unused variable __class__` and because we have
astroid at the version `1.6.x` we must upgrade pylint

### CODE REVIEW

**Comment by simobasso** [comment]
https://github.com/PyCQA/pylint-django/issues/120

**Comment by simobasso** [comment]
we have to wait https://github.com/PyCQA/pylint-django/pull/121 but tests are all green! 🎉 

when the PR will be merged in upstream and a new pylint-django will be released I'll update this pr

**Comment by simobasso** [comment]
@rtfpessoa updated! 🌮

**Comment by simobasso** [comment]
ehi @rtfpessoa do you need a rebase?

**Comment by rtfpessoa** [comment]
@simobasso I was able to do it in the UI. Should be merged soon if all goes ok.

**Comment by simobasso** [comment]
🎉

**Pull request merged**
