### PR TITLE
build: bump pylint version

### PR DESCRIPTION
**Pull request by simobasso**
this is very useful to avoid https://github.com/PyCQA/pylint/issues/1784

### CODE REVIEW

**Comment by rtfpessoa** [comment]
@simobasso, thanks for your contribution. Can you amend the commit for CircleCI to start the build? (it was disabled for forks for some reason)

**Comment by simobasso** [comment]
Yep! I'll do asap

**Comment by simobasso** [comment]
Done!

**Comment by simobasso** [comment]
🎉  @rtfpessoa thx!

**Pull request merged**
